use std::collections::BTreeMap;

use musig2::secp256k1::PublicKey;
use rand::{rngs::OsRng, RngCore};

use crate::types::{Blockchain, Participant, Participants, SwapSession};

use crate::types::SwapKeys;

/// Generates and returns a `SwapKeys` instance containing cryptographic keys for transaction signing.
///
/// This function performs the following tasks:
/// 1. Generates a random 256-bit secret key for use in the musig2 secp256k1 scheme.
/// 2. Derives the corresponding public key from the generated secret key.
/// 3. Generates a random 256-bit Ed25519 signing key for Cardano lock transaction signing, and derives
///    the corresponding verifying key.
///
/// # Returns
/// A `SwapKeys` structure populated with the following keys:
/// - `secret_key`: The randomly generated secp256k1 secret key.
/// - `public_key`: The public key derived from the secp256k1 secret key.
/// - `cardano_wallet_secret_key`: A vector representation of the Ed25519 signing key.
/// - `cardano_wallet_public_key`: A vector representation of the Ed25519 verifying key.
///
/// # Panics
/// This function will panic if:
/// - The random bytes generated for the secp256k1 secret key are invalid.
/// - Any cryptographic operation fails to produce results (e.g., invalid key generation).
///
///
pub fn make_swap_keys() -> SwapKeys {
    let mut bytes = [0u8; 32];
    OsRng.fill_bytes(&mut bytes);
    let secret_key = musig2::secp256k1::SecretKey::from_byte_array(bytes).unwrap();
    let public_key = musig2::secp256k1::PublicKey::from_secret_key(
        &musig2::secp256k1::Secp256k1::new(),
        &secret_key,
    );

    // generate Ed25519 keys for Cardano lock tx signing
    let mut ed25519_bytes = [0u8; 32];
    OsRng.fill_bytes(&mut ed25519_bytes);
    let ed25519_signing_key = ed25519_dalek::SigningKey::from_bytes(&ed25519_bytes);
    let ed25519_verifying_key = ed25519_signing_key.verifying_key();

    SwapKeys {
        secret_key,
        public_key,
        cardano_wallet_secret_key: ed25519_signing_key.to_bytes().to_vec(),
        cardano_wallet_public_key: ed25519_verifying_key.to_bytes().to_vec(),
    }
}

/// Creates a `Participant` instance with the given properties and generates cryptographic keys.
///
/// # Parameters
/// - `id` (`u8`): A unique identifier for the participant.
/// - `is_me` (`bool`): A flag indicating whether the participant represents the current user.
///
/// # Returns
/// - `Participant`: The created participant object with initialized properties.
///
/// # Panics
/// - This function will panic if the secret key cannot be derived from the generated byte array.
///
pub fn make_participant(id: u8, is_me: bool) -> Participant {
    let mut bytes = [0u8; 32];
    _ = OsRng.try_fill_bytes(&mut bytes);
    let secret_key = musig2::secp256k1::SecretKey::from_byte_array(bytes).unwrap();
    let public_key = musig2::secp256k1::PublicKey::from_secret_key(
        &musig2::secp256k1::Secp256k1::new(),
        &secret_key,
    );
    Participant {
        id,
        blockchain: Blockchain::Bitcoin,
        tcp_address: format!("127.0.0.1:90{id:02}"),
        target_participant: if id == 1 { 2 } else { 1 },
        amount_locking: 100,
        amount_claiming: 100,
        is_me,
        secp256k1_public_key: public_key.to_string(),
                cardano_wallet_public_key: vec![],
        funding_utxo_txid: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
            .to_string(),
        funding_utxo_vout: 0,
    }
}

/// Creates and returns a `Participants` instance, which is a `BTreeMap`
/// mapping participant IDs to their corresponding participant data.
///
/// This function initializes a `BTreeMap` and inserts two participants:
/// - Participant with ID `1`, created as active (`true`).
/// - Participant with ID `2`, created as inactive (`false`).
///
/// # Returns
/// A `Participants` instance containing the initialized participant data.
///
pub fn make_participants() -> Participants {
    let mut participants = BTreeMap::new();
    participants.insert(1, make_participant(1, true));
    participants.insert(2, make_participant(2, false));
    participants
}

/// Creates a new `SwapSession` instance with the specified session ID and default parameters.
///
/// # Parameters
///
/// * `id` - A `u64` value representing the unique identifier for the session.
///
/// # Returns
///
/// Returns a `SwapSession` instance initialized with:
/// - The provided session ID (`id`).
/// - A default set of participants, created by calling the `make_participants()` function.
/// - Initial values for other fields set to `0`.
///
/// Note
/// - The function assumes the existence of `SwapSession::new` and `make_participants()`
///   with appropriate definitions to support this implementation.
pub fn make_session(id: u64) -> SwapSession {
    SwapSession::new(id, make_participants(), 0, 0, 5_000, 2_000_000)
}

/// Generates a specified number of swap keys and their associated public keys.
///
/// # Parameters
///
/// * `n` - The number of swap keys to generate.
///
/// # Returns
///
/// A tuple containing:
/// - A `Vec<SwapKeys>`: The generated swap keys.
/// - A `Vec<PublicKey>`: The public keys extracted from the generated swap keys.
///
/// # Notes
///
/// - The function internally uses `make_swap_keys()` to generate each `SwapKeys`
///   and extracts the `public_key` field for the corresponding public key vector.
pub fn make_pubkeys(n: usize) -> (Vec<SwapKeys>, Vec<PublicKey>) {
    let keys: Vec<SwapKeys> = (0..n).map(|_| make_swap_keys()).collect();
    let pubkeys = keys.iter().map(|k| k.public_key).collect();
    (keys, pubkeys)
}

/// Generates a 256-bit (32-byte) cryptographically secure random seed.
///
/// # Returns
///
/// A `[u8; 32]` array containing 32 random bytes. The randomness is sourced
/// from the operating system's cryptographically secure random number generator
/// through `OsRng`.
///
/// # Notes
///
/// - This function uses `OsRng`, which relies on the operating system's
///   entropy sources. Ensure the platform provides sufficient entropy for
///   secure random number generation.
pub fn make_seed() -> [u8; 32] {
    let mut seed = [0u8; 32];
    OsRng.fill_bytes(&mut seed);
    seed
}

/// Constructs a new `Participant` with the provided parameters.
///
/// # Parameters
/// - `id` (`u8`): The unique identifier of the participant.
///   - It is used to determine the participant's TCP address and the target participant in the configuration.
/// - `is_me` (`bool`): Specifies whether the participant represents the current instance.
///   - `true` if it is the current instance; otherwise, `false`.
/// - `public_key` (`PublicKey`): The Secp256k1 public key of the participant.
///
/// # Returns
/// - A `Participant` instance configured with the given parameters, default values, and computed properties.
///
/// ## Default and Computed Values
/// - `blockchain`: Always set to `Blockchain::Bitcoin`.
/// - `tcp_address`: Derived from the `id` in the format `127.0.0.1:91{id:02}`.
///   - Example: If `id` is 5, the TCP address will be `127.0.0.1:9105`.
/// - `target_participant`: If the `id` is 1, the value is set to `2`. Otherwise, it defaults to `1`.
/// - `amount_locking`: Set to `100`.
/// - `amount_claiming`: Set to `100`.
/// - `secp256k1_public_key`: Converted to a string representation of the provided `public_key`.
/// - `cardano_wallet_public_key`: Initialized as an empty vector.
/// - `funding_utxo_txid`: Hardcoded to `"a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"`.
/// - `funding_utxo_vout`: Always set to `0`.
///
pub fn make_participant_with_key(id: u8, is_me: bool, public_key: PublicKey) -> Participant {
    Participant {
        id,
        blockchain: Blockchain::Bitcoin,
        tcp_address: format!("127.0.0.1:91{id:02}"),
        target_participant: if id == 1 { 2 } else { 1 },
        amount_locking: 100,
        amount_claiming: 100,
        is_me,
        secp256k1_public_key: public_key.to_string(),
        cardano_wallet_public_key: vec![],
        funding_utxo_txid: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
            .to_string(),
        funding_utxo_vout: 0,
    }
}

/// Creates a `Participants` map from a slice of `SwapKeys`, marking one participant as "self".
///
/// # Parameters
///
/// * `keys` - A slice of `SwapKeys`, where each `SwapKeys` represents the cryptographic keys
///   needed to define a participant. Each key includes a public key that will be used for the
///   participant creation.
/// * `me_index` - The index in the `keys` slice that corresponds to the "self" participant.
///   The participant with this index will be marked as the current user.
///
/// # Returns
///
/// Returns a `Participants` map, which is a `BTreeMap` where:
/// - The key is a `u8` identifier for each participant, starting from `1`.
/// - The value is the participant generated using the `make_participant_with_key` function,
///   including their ID, whether they are the "self" participant, and their public key.
///
/// # Panics
///
/// This function does not perform bounds checking on `me_index`. If `me_index` is not within
/// the bounds of the `keys` slice, the behavior of this function is undefined.
///
pub fn make_participants_from(keys: &[SwapKeys], me_index: usize) -> Participants {
    let mut participants = BTreeMap::new();
    for (i, key) in keys.iter().enumerate() {
        let id = (i + 1) as u8;
        participants.insert(id, make_participant_with_key(id, i == me_index, key.public_key));
    }
    participants
}
